# Generated by Django 3.1 on 2021-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0004_auto_20211209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('header_menu', 'Верхнее меню')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
