# Generated by Django 3.1 on 2021-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='rating_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='rating_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тип'),
        ),
    ]
