# Generated by Django 3.1 on 2021-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20211210_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpage',
            name='rating_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
