# Generated by Django 3.1 on 2021-12-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20211210_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
