# Generated by Django 3.1 on 2021-12-13 03:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='ДАТА ЗАЕЗДА')),
                ('check_out', models.DateField(verbose_name='ДАТА ВЫЕЗДА')),
                ('adults', models.IntegerField(verbose_name='ВЗРОСЛЫЕ')),
                ('kids', models.IntegerField(verbose_name='ДЕТИ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Бронирование гостиницы',
                'verbose_name_plural': 'Бронирование гостиниц',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.CharField(max_length=250, verbose_name='Cодержание')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='home.homepage', verbose_name='Страница (привязка)')),
            ],
            options={
                'verbose_name': 'Элемент рекомендация',
                'verbose_name_plural': 'Элементы рекомендация',
            },
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('content', models.CharField(max_length=250, verbose_name='Cодержание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='home.homepage', verbose_name='Страница (привязка)')),
            ],
            options={
                'verbose_name': 'Элемент причина',
                'verbose_name_plural': 'Элементы причина',
            },
        ),
    ]
